In [2]:
# Problem 1
import numpy as np


arr1 = np.empty((2,2))
print(f"arrary1:\n {arr1}\n")

arr2 = np.ones((4,2))
print(f"arr2: \n {arr2}\n")

arr3 = np.full((3,3), 4)
print(f"arr3: \n {arr3}\n")

arr4 = np.full_like(arr3, 45)
print(f"arr4: \n {arr4}\n")

arr5 = np.full_like(arr2, 66)
print(f"arr5: \n {arr5}\n")

new_list = [1,2,3,4]
print(f" arr6:\n{np.array(new_list)}\n")


arrary1:
 [[0. 0.]
 [0. 0.]]

arr2: 
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

arr3: 
 [[4 4 4]
 [4 4 4]
 [4 4 4]]

arr4: 
 [[45 45 45]
 [45 45 45]
 [45 45 45]]

arr5: 
 [[66. 66.]
 [66. 66.]
 [66. 66.]
 [66. 66.]]

 arr6:
[1 2 3 4]



In [17]:
arr = np.arange(10, 50)
print(arr)

arr = np.arange(9).reshape(3,3)
print(arr)

arr = np.eye(3)
print(arr)

arr = np.random.random(30)

mean_value = arr.mean()

print(arr)
print("Mean:", mean_value)

arr = np.random.random((10,10))

print(arr)

print("Minimum:", arr.min())
print("Maximum:", arr.max())

arr = np.zeros(10)

arr[4] = 1

print(arr)

arr = np.array([1,2,0,0,4,0])

reversed_arr = arr[::-1]

print("reversed adsadsaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaray",reversed_arr)


arr = np.ones((5,5))

arr[1:-1, 1:-1] = 0

print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[0.92864594 0.01423542 0.24031138 0.97788373 0.39138239 0.62205864
 0.92580655 0.76228857 0.0462499  0.18127711 0.8712845  0.91368695
 0.41661288 0.72228536 0.228264   0.57110356 0.4395599  0.53706598
 0.75060368 0.72205438 0.91259433 0.96732481 0.42700264 0.24391106
 0.88736908 0.33803671 0.03477651 0.66521708 0.1645339  0.18034897]
Mean: 0.5361258635634853
[[0.14241574 0.54595785 0.94666376 0.14054581 0.73586295 0.80006282
  0.23256572 0.98366557 0.36351031 0.33492633]
 [0.15836875 0.72353239 0.89249538 0.32096409 0.54006432 0.20094954
  0.99326919 0.70647236 0.94664781 0.38154264]
 [0.17941819 0.58348245 0.8298583  0.24423697 0.21209361 0.55569587
  0.08548302 0.81617015 0.7078384  0.63473252]
 [0.84014635 0.62203387 0.55411613 0.87670542 0.96563917 0.62261654
  0.53774781 0.45220961 0.39692193 0.9

In [29]:
#problem 3
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11,12])

print(x + y)
print(x - y)
print(x * 3)
print(x ** 2)
print(np.dot(v,w))
print(np.dot(x,v))
print(np.dot(x,y))

print(np.concatenate((x,y), axis=0))
print(np.concatenate((v,w), axis=0))

try:
    np.concatenate((x,v))
except Exception as e:
    print(f"Error occured: {e} because concatioation of matrix is only possible of their dimensions are same")


[[ 6  8]
 [10 13]]
[[-4 -4]
 [-4 -3]]
[[ 3  6]
 [ 9 15]]
[[ 1  4]
 [ 9 25]]
219
[29 77]
[[19 22]
 [50 58]]
[[1 2]
 [3 5]
 [5 6]
 [7 8]]
[ 9 10 11 12]
Error occured: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s) because concatioation of matrix is only possible of their dimensions are same


In [32]:
# Problem 3

A = np.array([[3,4],
              [7,8]])

B = np.array([[5,3],
              [2,1]])

A_inv = np.linalg.inv(A)

result = np.dot(A, A_inv)

print("A inverse:\n", A_inv)
print("A * A_inv:\n", np.round(result, 5))

A inverse:
 [[-2.    1.  ]
 [ 1.75 -0.75]]
A * A_inv:
 [[1. 0.]
 [0. 1.]]


In [33]:
AB = np.dot(A,B)
BA = np.dot(B,A)

print("AB:\n", AB)
print("BA:\n", BA)

AB:
 [[23 13]
 [51 29]]
BA:
 [[36 44]
 [13 16]]


In [34]:
left = np.transpose(AB)

right = np.dot(B.T, A.T)

print("(AB)^T:\n", left)
print("B^T A^T:\n", right)

(AB)^T:
 [[23 51]
 [13 29]]
B^T A^T:
 [[23 51]
 [13 29]]


In [38]:
A = np.array([
    [2,-3,1],
    [1,-1,2],
    [3,1,-1]
])
B = np.array([-1,-3,9])

A_inv = np.linalg.inv(A)

X = np.dot(A_inv, B)

print("Solution:", X)

Solution: [ 2.  1. -2.]


Solution: [ 2.  1. -2.]
